import '@/global.css'
import { Metadata } from 'next';


export const metadata: Metadata = {
  title: "3d playground",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  function cn(className: any, arg1: string): string {
    throw new Error('Function not implemented.');
  }

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={
        "bg-white dark:bg-[#313338]"
      }>
        {children}
      </body>
    </html>

  );
}
